### ISSUE TITLE
Audio and Video not working

### ISSUE THREAD

**Issue by BenevolentDM** [luvolondon/fvtt-module-jitsiwebrtc#35] opened 2020-10-26 18:28 UTC
With Foundryvtt version 0.7.5 and 5e rule set version .98 I am experiencing trouble with all players not seeing the DM (me) and some players not seeing each other and not hearing each other. Also when audio is set to voice activation the mic isn't activating when I talk.

**Comment by bekriebel** [comment] 2020-10-26 20:02
Closing as a duplicate of #34

**Closed as completed by bekriebel** 2020-10-26 20:02 UTC
