### ISSUE TITLE
With no Webcam Audio fails

### ISSUE THREAD

**Issue by SimmyD** [luvolondon/fvtt-module-jitsiwebrtc#28] opened 2020-09-12 09:50 UTC
I have users that do not have webcams and leave the video input as "Default Source" which is the default.

When they connect they expect their mics to at least work.  It doesnt connect their mics though. (they can hear and see other people though)

If they go and select "disable sending camera" then their mic's connect and they can communicate.

I am checking if i have done something wrong?  I have replicated this by removing my webcam and following the above steps.

**Comment by Mist-Hunter** [comment] 2020-09-30 21:38
Just chiming in to add that two of my users have seen this also. 

"Default" on video, when no video source is present causes audio to also not work. I'm not sure if this was intended, but it was not intuitive to us. 

Either way, thanks for the awesome module!

**Comment by leWebslinger** [comment] 2020-11-01 10:20
this would explain a malfunction experienced by one of my players.
All programs are self hosted
Foundry(0.7.5)
Jitsi module (0.4.1)
update+upgrade done.

**Comment by caewok** [comment] 2020-11-03 18:22
For the player, try clicking the settings gear from the player video window. Click the devices tab, and then select disable sending camera under the video capture device setting. This worked for one of our players who did not have a camera. Otherwise, we got the same bug where there was no audio for the player that did not have a camera.

**Comment by bekriebel** [comment] 2020-11-10 00:02
Will be fixed in the next release

**Closed as completed** 2020-11-10 00:02 UTC
Labels: bug

**Comment by bekriebel** [comment] 2020-11-10 06:26
This should now be fixed with v0.4.3
