### ISSUE TITLE
Changes to Jitsi Docker config required to correctly generate config.js

### ISSUE THREAD

**Issue by eclarke12** [luvolondon/fvtt-module-jitsiwebrtc#42] opened 2020-11-09 01:40 UTC
Foundry: 076
Module: 042

I have a custom Jitsi host at `voice.mydomain.com` however it appears the module isn't correctly concatenating the host into the bosh call:
![image](https://user-images.githubusercontent.com/42503461/98490911-04b48200-21e8-11eb-97e8-980c5544c6fa.png)

this causes the module to try and call bosh on the existing Foundry web host (eg. `vtt.mydomain.com`) which then fails:
![image](https://media.discordapp.net/attachments/722566083499786352/775168576876576778/unknown.png)

**Comment by bekriebel** [comment] 2020-11-09 07:32
We can add backup logic to this. However, the cause of the error is that likely your jitsi-meet config.js file does not have the bosh URL information in it. We are now reading information from that file.

We can make it so it fall back to the default format if it isn't available in the config. However, I'd recommend updating your config.js file to have the proper info. Alternatively, you can go under Module Settings and enable "Use custom Jitsi URLS" and make sure the correct URL is entered under "Jitsi Bosh URL" after that option is enabled.

**Comment by eclarke12** [comment] 2020-11-09 15:51
I tried with the default and custom URLs in settings and it still has
the same problem.

I will try manually editing the config.js

**Comment by eclarke12** [comment] 2020-11-09 16:36
I don't see any file named `jitsi-meet-config.js` in my module folder:
![image](https://user-images.githubusercontent.com/42503461/98568966-8945e580-2266-11eb-875d-e03a5e8f02c8.png)

Here's my module config:
![image](https://user-images.githubusercontent.com/42503461/98568880-6fa49e00-2266-11eb-9d3a-fd26e181da8a.png)

And my A/V config:
![image](https://user-images.githubusercontent.com/42503461/98569065-a7134a80-2266-11eb-96c5-149e48814a13.png)

**Comment by eclarke12** [comment] 2020-11-09 17:40
I think the issue lies here: 
https://github.com/jitsi/docker-jitsi-meet/issues/570
https://github.com/jitsi/docker-jitsi-meet/issues/768
https://github.com/jitsi/docker-jitsi-meet/issues/773

I'm going to explore this further with my docker container configs

**Comment by bekriebel** [comment] 2020-11-09 17:54
Yeah, the config.js would be on the jitsi server side. However, setting the custom URLs should still work and I can still make it so we attempt to fall back to default values where needed.

**Comment by eclarke12** [comment] 2020-11-09 18:34
OK I think maybe there is some effort required on the module side? I checked my config.js again and the custom domain info is already in there, but the `bosh` property seems like it needs to be concatenated with the domain to ensure it doesn't simply append to the Foundry domain?
![image](https://user-images.githubusercontent.com/42503461/98581979-26a91580-2277-11eb-9bc3-fc4e2427ebd0.png)

**Comment by bekriebel** [comment] 2020-11-09 18:45
Oh, it has an entry - it's just invalid. That's not what I expected.

That is a bug on on the configs from the jitsi server, then. It should include the full domain just like the other configs above it. I could probably add some logic to prepend the default domain if it starts with single `/`, but that really should be fixed on the jitsi server side with the docker setup or wherever else that is coming from.

For example, this is the config for the beta public jitsi server that we use by default: https://beta.meet.jit.si/config.js

**Comment by bekriebel** [comment] 2020-11-10 06:25
With the new 0.4.3 release, I didn't make us automatically fix the bosh setting. However, it should properly allow you to use the custom settings. If you can't fix the config file on the jitsi server, I would try enabling the option to use custom settings on the module settings and make sure the bosh URL is set properly there.

**Closed as completed by bekriebel** 2020-11-10 06:25 UTC
